export const PAGE_ENUMS = {
  OVERVIEW: {
    DASHBOARD: 'DASHBOARD',
  },

  USER_MGT: {
    ADMINS: 'ADMINS',
    ROLES_AND_PRIVILEGES: 'ROLES_AND_PRIVILEGES',
    USERS: 'USERS',
    AGENTS: 'AGENTS',
    MERCHANTS: 'MERCHANTS',
    AGGREGATORS: 'AGGREGATORS',
    AGGREGATOR_UPLOADS: 'AGGREGATOR_UPLOADS',
  },

  COMPLIANCE: {
    ONBOARDINGS: 'ONBOARDINGS',
    BVN: 'BVN_VERIFICATION',
    NIN: 'NIN_VERIFICATION',
    ADDRESS_VERIFICATION: 'ADDRESS_VERIFICATION',
    CAC_VERIFICATION: 'CAC_VERIFICATION',
    BUSINESS_APPLICATIONS: 'BUSINESS_APPLICATIONS',
    LIVENESS_CHECKS: 'LIVENESS_CHECKS',
    ACCOUNT_DELETION_REQUESTS: 'ACCOUNT_DELETION_REQUESTS',
  },

  MONITORING: {
    FRAUD_MONITORING: 'FRAUD_MONITORING',
    USER_ANALYTICS: 'USER_ANALYTICS',
    RAPID_FIRE: 'RAPID_FIRE',
  },

  TRANSACTIONS: {
    TRANSACTION_HISTORY: 'TRANSACTION_HISTORY',
    MANUAL_DEBIT_CREDIT: 'MANUAL_DEBIT_CREDIT',
    CASHFLOW: 'CASHFLOW',
    OVERSPENT_USERS: 'OVERSPENT_USERS',
    SETTLEMENTS: 'SETTLEMENTS',
    DISPUTES: 'DISPUTES',
  },

  FINANCE: {
    WALLETS: 'WALLETS',
    STATEMENTS: 'STATEMENTS',
    GENERAL_LEDGER: 'GENERAL_LEDGER',
    LEDGER_ACCOUNTS: 'LEDGER_ACCOUNTS',
    TRIAL_BALANCE: 'TRIAL_BALANCE',
    PROVIDER_BALANCES: 'PROVIDER_BALANCES',
    FUNDING_ALERTS: 'FUNDING_ALERTS',
    BULK_PAYMENTS: 'BULK_PAYMENTS',
    ADMIN_TRANSFERS: 'ADMIN_TRANSFERS',
    RECONCILIATION_UPLOADS: 'RECONCILIATION_UPLOADS',
    RECONCILIATION_CONFIG: 'RECONCILIATION_CONFIG',
    REVENUE: 'REVENUE',
    RECEIVABLES: 'RECEIVABLES',
    PAYABLES: 'PAYABLES',
    PROVIDER_FLOAT: 'PROVIDER_FLOAT',
    VA_ECONOMICS: 'VA_ECONOMICS',
    PERIOD_CLOSES: 'PERIOD_CLOSES',
    VIRTUAL_FUNDING_REPUSH: 'VIRTUAL_FUNDING_REPUSH',
  },

  GOVERNANCE: {
    CHECKERS: 'CHECKERS',
    APPROVALS: 'APPROVALS',
  },

  OPERATIONS: {
    TERMINALS: 'TERMINALS',
    TERMINAL_IDS: 'TERMINAL_IDS',
    INSTANT_SETTLEMENTS: 'INSTANT_SETTLEMENTS',
    STOCK_PURCHASE: 'STOCK_PURCHASE',
    STOCK_UTILIZATION: 'STOCK_UTILIZATION',
    POS_LEASES: 'POS_LEASES',
  },

  SYSTEM: {
    AUDIT_LOGS: 'AUDIT_LOGS',
    API_PERFORMANCE: 'API_PERFORMANCE',
    API_TRAFFIC: 'API_TRAFFIC',
    HTTP_TRAFFIC: 'HTTP_TRAFFIC',
    ISO_TRAFFIC: 'ISO_TRAFFIC',
    BROADCAST_MESSAGES: 'BROADCAST_MESSAGES',
  },

  SETTINGS: {
    CONFIGURATIONS: 'CONFIGURATIONS',
    LIMITS: 'LIMITS',
    COMMISSIONS: 'COMMISSIONS',
    CHARGES: 'CHARGES',
    AVAILABILITY: 'AVAILABILITY',
    PROVIDERS: 'PROVIDERS',
    FAILOVER: 'FAILOVER',
    DATA_PLANS: 'DATA_PLANS',
    MAX_BALANCE: 'MAX_BALANCE',
    POS_LEASE_FEES: 'POS_LEASE_FEES',
    TARGET_GRACE: 'TARGET_GRACE',
    POS_APP: 'POS_APP',
    CARD_KEYS: 'CARD_KEYS',
    STAGING_RESET: 'STAGING_RESET',
  },
};
